apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/dongwenjuan/project-config-inter:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/dongwenjuan/project-config-inter:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: project-config-inter
        chartPath: charts/project-config-inter
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/dongwenjuan/project-config-inter"
          image.tag: "{{.DIGEST_HEX}}"
